#include<bits/stdc++.h>
using namespace std;
#define ll long long
typedef pair<ll,ll> ii;
typedef vector<ll> vi;
typedef vector<ii> vii;
#define read(arr,n) int arr[n]; for(int i=0;i<n;i++)cin>>arr[i];

int main()
{
    ios_base::sync_with_stdio(0);
      cin.tie(0);
      cout.tie(0);
      ll n,m,q;cin>>n>>m>>q;
      ll a[n];
      for(int i=0;i<n;i++)cin>>a[i];
      ii t[m];
      ll t1[m];
      ll a1=m;
      for(ll i=0;i<m;i++)
      {
        cin>>t[i].first;
        cin>>t[i].second;
        cin>>t1[i];
      }
      ll s[n] {0};
      while(q--)
      {
        ll l,r;cin>>l>>r;
        for(ll i=l;i<=r;i++)
        {
            

        }
       
      }

}
